Update api-setup.md
searchkit schema giving the error  
GraphQLError: Syntax Error: Expected Name, found }
due to the empty object of the type HitFields